# This file is the thing you have to config to match your application
IMPORT_PRODUCT_SETTINGS = {
  :column_mappings => { #Change these for manual mapping of product fields to the CSV file
      #:id => 0,
      :name => 1,
      :description => 2,
      :sku => 3,
      :master_price => 4,
      :cost_price => 5,
      :weight => 6,
      :height => 7,
      :width => 8,
      :depth => 9,
      :color => 10,
      :color_code => 11,
      :energy_star => 12,
      :nbl_code => 13,
      :free_delivery => 14,
      :meta_description => 15,
      :meta_keywords => 16,
      :permalink => 17,
      :count_on_hand => 18,
      :files => 21,
      :brand => 20,
      :category => 19
  },
  :create_missing_taxonomies => true,
  :taxonomy_fields => [:category, :brand, :free_delivery, :nbl_code, :energy_star, :color_code], #Fields that should automatically be parsed for taxons to associate
  :asset_field => [:files], #Image fields that should be parsed for image locations
  :product_image_path => "#{Rails.root}/public/product_image/file/", #The location of images on disk
  :product_document_path => "#{Rails.root}/public/product_document/file/", #The location of images on disk
  :rows_to_skip => 1, #If your CSV file will have headers, this field changes how many rows the reader will skip
  :log_to => File.join(Rails.root, '/log/', "import_products_#{Rails.env}.log"), #Where to log to
  :destroy_original_products => false, #Delete the products originally in the database after the import?
  :first_row_is_headings => false, #Reads column names from first row if set to true.
  :create_variants => true, #Compares products and creates a variant if that product already exists.
  :variant_comparator_field => :permalink, #Which product field to detect duplicates on
  :multi_domain_importing => false, #If Spree's multi_domain extension is installed, associates products with store
  :store_field => :store_code #Which field of the column mappings contains either the store id or store code?
}
